### ISSUE TITLE
Where is F?

### ISSUE THREAD

**Issue by ghost** [diegoceccarelli/bm25f-solr-ranking#1]
BM25 leverages average document length.

BM25F as defined by okapai papers involves MULTIPLE features; not 1 specific one.

Does this plugin support n features of user defined type? Is that a next rev.

Its great to have BM25. But F is a conspicous and complex step beyond....

**Comment by diegoceccarelli** [comment]
Hei cwsusa, did you have a look to the documentation? 
https://docs.google.com/document/d/1zphYX1oY1S4n8Y6t4D_rPzpSobR0iDzIxDqOEgsVBbs/edit
please observe that this version is for solr3.0. 

I'm currently working on the BM25F solr4.0 version (while BM25 is yet supported in solr4.0),
I'll release it when it will be stable

**Comment by ghost** [comment]
HI Diego: I was excited to see someone taking this one. I did look at the documentation and it calls the plugin BM25F but only supports the addition of lengths over BM23 and the others.

Glad to hear you’re working on a 4.0 version. Let me know if you want to offload any tasks.

Regards,

Will Martin

**Comment by ghost** [comment]
Robertson, Burges et al
Copyright 2006 ACM 1595934332/06/0011

"Optimisation Methods for Ranking Functions with Multiple Parameters"

**Comment by ghost** [comment]
And there is always the accepted work of Singhal et al, on Pivoted Length normalization; addressing the empirically (by myself with others at a large ISP) observed bias toward certain lengths in ranking functions that incorporate this feature.

**Comment by diegoceccarelli** [comment]
hei Will, thanks for your comments, I'll have a look to paper you suggested, but I don't understand what do you mean by 

> it calls the plugin BM25F but only supports the addition of lengths over BM23 and the others. 

I think I implemented BM25F as described in literature, and it supports the boosts on lengths, on fields and 
the saturation parameter (k1), what do you mean by " but only supports the addition of lengths over BM23" ?

**Comment by ghost** [comment]
My bad. I missed part of the document the previous read. When I work with IR engines I have the habit of looking out and in this case seeing features as those internal actors for a given query ... inside lucene. However from the Solr view Fields is a much more natural conflation with that term. Not even sure if I'm remembering all the papers I used right anyway.

So ....   I'll join the queue waiting for Solr 4.0 plugin. Thanks.

**Comment by ghost** [comment]
You should close this ticket.
