### ISSUE TITLE
bm25f in elasticsearch

### ISSUE THREAD

**Issue by faliev** [diegoceccarelli/bm25f-solr-ranking#2]
Hi Diego,

First, thank you for this library. 

I'd like to start using bm25f in ElasticSearch, so I wanted to ask you if it is ok for me to fork it and re-use your code? 

Again, thank you for your amazing contribution.

regards, 
Farid.

**Comment by diegoceccarelli** [comment]
Dear @faliev 

Thanks for writing! sure that you can reuse my code! But I've to warn you that this is 
for Solr/Lucene 3.0, I've developed the version for Solr/Lucene4.0+ few months ago
for the Europeana website. You can find the new version here: 

https://github.com/diegoceccarelli/contrib/tree/master/bm25f-ranking

Please feel free to open issues/add patches etc, you are super welcome ;) 

cheers,
Diego
